<?php
use App\Auth;use App\DB;use App\Otp;
$action=$_GET['action']??'';$method=$_SERVER['REQUEST_METHOD']??'GET';$in=$method==='GET'?$_GET:json_input();
try{
 if($action==='otp-send'&&$method==='POST'){[$ok,$message]=Otp::send((string)($in['mobile']??''));json_response(['ok'=>$ok,'message'=>$message],$ok?200:422);}
 if($action==='otp-verify'&&$method==='POST'){[$ok,$message]=Otp::verify((string)($in['mobile']??''),(string)($in['code']??''));json_response(['ok'=>$ok,'message'=>$message,'csrf'=>$ok?csrf_token():null],$ok?200:422);}
 if($action==='password-login'&&$method==='POST'){[$ok,$message]=Auth::passwordLogin((string)($in['mobile']??''),(string)($in['password']??''));json_response(['ok'=>$ok,'message'=>$message,'csrf'=>$ok?csrf_token():null],$ok?200:422);}
 Auth::require();if($method!=='GET')Auth::csrf();$uid=Auth::id();
 if($action==='dashboard'){
  $stats=DB::one("SELECT (SELECT COUNT(*) FROM companies WHERE user_id=?) companies,(SELECT COUNT(*) FROM customers WHERE user_id=?) customers,(SELECT COUNT(*) FROM catalog_items WHERE user_id=? AND is_active=1) catalog,(SELECT COUNT(*) FROM quotes WHERE user_id=?) quotes,(SELECT COUNT(*) FROM quotes WHERE user_id=? AND status='draft') drafts,(SELECT COALESCE(SUM(total),0) FROM quotes WHERE user_id=? AND status='issued') issued_total",[$uid,$uid,$uid,$uid,$uid,$uid]);
  $recent=DB::all("SELECT q.id,q.quote_number,q.status,q.issue_date,q.total,c.name company_name,COALESCE(cu.name,'') customer_name FROM quotes q JOIN companies c ON c.id=q.company_id LEFT JOIN customers cu ON cu.id=q.customer_id AND cu.user_id=q.user_id WHERE q.user_id=? ORDER BY q.id DESC LIMIT 8",[$uid]);
  json_response(['ok'=>true,'data'=>['stats'=>$stats,'recent'=>$recent,'user'=>Auth::user()]]);
 }
 if($action==='profile-save'&&$method==='POST'){
  $name=trim((string)($in['name']??''));$email=trim((string)($in['email']??''));if($name!==''&&mb_strlen($name)<2)json_response(['ok'=>false,'message'=>'نام باید حداقل دو نویسه باشد.'],422);if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))json_response(['ok'=>false,'message'=>'ایمیل معتبر نیست.'],422);
  $current=DB::one('SELECT password_hash FROM users WHERE id=?',[$uid]);$new=(string)($in['new_password']??'');$confirm=(string)($in['password_confirmation']??'');
  if($new!==''){if(strlen($new)<8||!preg_match('/[A-Za-z]/',$new)||!preg_match('/\d/',$new))json_response(['ok'=>false,'message'=>'رمز باید حداقل ۸ نویسه و شامل حرف و عدد باشد.'],422);if(!hash_equals($new,$confirm))json_response(['ok'=>false,'message'=>'تکرار رمز یکسان نیست.'],422);if($current&&$current['password_hash']&&!password_verify((string)($in['current_password']??''),$current['password_hash']))json_response(['ok'=>false,'message'=>'رمز فعلی نادرست است.'],422);$hash=password_hash($new,PASSWORD_DEFAULT);DB::exec('UPDATE users SET name=?,email=?,password_hash=? WHERE id=?',[$name?:null,$email?:null,$hash,$uid]);}
  else DB::exec('UPDATE users SET name=?,email=? WHERE id=?',[$name?:null,$email?:null,$uid]);
  audit($uid,null,'profile_update','user',$uid,null,['name'=>$name,'email'=>$email,'password_changed'=>$new!=='']);json_response(['ok'=>true,'message'=>'پروفایل ذخیره شد.','data'=>Auth::user()]);
 }
 if(str_starts_with($action,'admin-'))Auth::requireAdmin();
 if($action==='admin-overview'){
  $stats=DB::one("SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM users WHERE is_active=1) active_users,(SELECT COUNT(*) FROM companies) companies,(SELECT COUNT(*) FROM catalog_items WHERE is_active=1) catalog,(SELECT COUNT(*) FROM quotes) quotes,(SELECT COALESCE(SUM(total),0) FROM quotes WHERE status='issued') issued_total");
  json_response(['ok'=>true,'data'=>$stats]);
 }
 if($action==='admin-users'){
  $q='%'.trim((string)($in['q']??'')).'%';$users=DB::all('SELECT u.id,u.mobile,u.name,u.email,u.role,u.is_active,u.last_login_at,u.created_at,(SELECT COUNT(*) FROM companies c WHERE c.user_id=u.id) companies_count,(SELECT COUNT(*) FROM quotes q WHERE q.user_id=u.id) quotes_count FROM users u WHERE u.mobile LIKE ? OR u.name LIKE ? OR u.email LIKE ? ORDER BY u.id DESC LIMIT 200',[$q,$q,$q]);json_response(['ok'=>true,'data'=>$users]);
 }
 if($action==='admin-user-save'&&$method==='POST'){
  $id=(int)($in['id']??0);$role=($in['role']??'user')==='admin'?'admin':'user';$active=!empty($in['is_active'])?1:0;if($id===$uid&&(!$active||$role!=='admin'))json_response(['ok'=>false,'message'=>'نمی‌توانید دسترسی مدیر فعلی را حذف یا حساب خود را مسدود کنید.'],422);
  $before=DB::one('SELECT id,role,is_active FROM users WHERE id=?',[$id]);if(!$before)json_response(['ok'=>false,'message'=>'کاربر پیدا نشد.'],404);
  if($before['role']==='admin'&&($role!=='admin'||!$active)){ $admins=DB::one("SELECT COUNT(*) c FROM users WHERE role='admin' AND is_active=1");if((int)$admins['c']<=1)json_response(['ok'=>false,'message'=>'آخرین مدیر فعال قابل تنزل یا مسدودکردن نیست.'],422);}
  DB::exec('UPDATE users SET role=?,is_active=? WHERE id=?',[$role,$active,$id]);audit($uid,null,'admin_user_update','user',$id,$before,['role'=>$role,'is_active'=>$active]);json_response(['ok'=>true,'message'=>'وضعیت کاربر به‌روزرسانی شد.']);
 }
 if($action==='admin-catalog'){
  $q='%'.trim((string)($in['q']??'')).'%';$rows=DB::all('SELECT i.id,i.name,i.type,i.sku,i.unit,i.last_price,i.is_active,c.name company_name,u.id user_id,u.mobile user_mobile,u.name user_name FROM catalog_items i JOIN companies c ON c.id=i.company_id JOIN users u ON u.id=i.user_id WHERE i.name LIKE ? OR i.sku LIKE ? OR u.mobile LIKE ? ORDER BY i.id DESC LIMIT 300',[$q,$q,$q]);json_response(['ok'=>true,'data'=>$rows]);
 }
 if($action==='admin-catalog-save'&&$method==='POST'){
  $id=(int)($in['id']??0);$before=DB::one('SELECT * FROM catalog_items WHERE id=?',[$id]);if(!$before)json_response(['ok'=>false,'message'=>'مورد پیدا نشد.'],404);$name=trim((string)($in['name']??''));if(mb_strlen($name)<2)json_response(['ok'=>false,'message'=>'نام معتبر نیست.'],422);$type=($in['type']??'product')==='service'?'service':'product';$price=max(0,(float)($in['last_price']??0));$active=!empty($in['is_active'])?1:0;
  DB::exec('UPDATE catalog_items SET name=?,type=?,unit=?,last_price=?,is_active=? WHERE id=?',[$name,$type,trim((string)($in['unit']??'عدد')),$price,$active,$id]);audit($uid,(int)$before['company_id'],'admin_catalog_update','catalog_item',$id,$before,['name'=>$name,'type'=>$type,'last_price'=>$price,'is_active'=>$active]);json_response(['ok'=>true,'message'=>'کالا یا خدمت به‌روزرسانی شد.']);
 }
 if($action==='admin-settings'){
  $keys=['app.name','sms.from_number','sms.pattern_code','sms.otp_param','sms.auth_prefix','sms.share_pattern_code','sms.share_number_param','sms.share_password_param','sms.share_link_param','mail.from_address','otp.ttl_seconds','otp.resend_seconds'];$out=[];foreach($keys as $key)$out[$key]=\App\Settings::get($key,'');$out['sms.api_key_configured']=\App\Settings::get('sms.api_key',(string)env('IPPANEL_API_KEY',''))!=='';json_response(['ok'=>true,'data'=>$out]);
 }
 if($action==='admin-settings-save'&&$method==='POST'){
  $plain=['app.name','sms.from_number','sms.pattern_code','sms.otp_param','sms.auth_prefix','sms.share_pattern_code','sms.share_number_param','sms.share_password_param','sms.share_link_param','mail.from_address'];foreach($plain as $key)if(array_key_exists($key,$in))\App\Settings::set($key,trim((string)$in[$key]),false,$uid);
  $ttl=max(60,min(600,(int)($in['otp.ttl_seconds']??120)));$resend=max(30,min(300,(int)($in['otp.resend_seconds']??60)));\App\Settings::set('otp.ttl_seconds',(string)$ttl,false,$uid);\App\Settings::set('otp.resend_seconds',(string)$resend,false,$uid);
  if(trim((string)($in['sms.api_key']??''))!=='')\App\Settings::set('sms.api_key',trim((string)$in['sms.api_key']),true,$uid);
  audit($uid,null,'admin_settings_update','system',null,null,['keys'=>array_keys($in)]);json_response(['ok'=>true,'message'=>'تنظیمات سامانه ذخیره شد.']);
 }
 if($action==='admin-output-templates'){
  $rows=DB::all('SELECT * FROM output_templates ORDER BY is_default DESC,id DESC');foreach($rows as &$row)$row['config']=json_decode((string)$row['config_json'],true)?:[];unset($row['config_json']);json_response(['ok'=>true,'data'=>$rows]);
 }
 if($action==='admin-output-template-save'&&$method==='POST'){
  $id=(int)($in['id']??0);$name=trim((string)($in['name']??''));if(mb_strlen($name)<2)json_response(['ok'=>false,'message'=>'نام فرم خروجی الزامی است.'],422);$paper=in_array($in['paper_size']??'', ['a3','a4','a5','a6','letter','legal'],true)?$in['paper_size']:'a4';$orientation=($in['orientation']??'landscape')==='portrait'?'portrait':'landscape';$style=in_array($in['style']??'', ['formal','modern','minimal'],true)?$in['style']:'formal';
  $allowedColumns=['code','unit','quantity','unit_price','gross','discount','after_discount','tax','total'];$allowedSections=['seller','buyer','notes','payment','signatures','footer'];$columns=[];$sections=[];foreach($allowedColumns as $key)$columns[$key]=!empty($in['columns'][$key]);foreach($allowedSections as $key)$sections[$key]=!empty($in['sections'][$key]);$allowedOrder=['header','seller','buyer','items','notes','signatures','footer'];$order=array_values(array_intersect(is_array($in['order']??null)?$in['order']:[],$allowedOrder));foreach($allowedOrder as $key)if(!in_array($key,$order,true))$order[]=$key;$config=json_encode(['columns'=>$columns,'sections'=>$sections,'order'=>$order],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);$default=!empty($in['is_default'])?1:0;$active=$default?1:(!empty($in['is_active'])?1:0);
  DB::pdo()->beginTransaction();if($default)DB::exec('UPDATE output_templates SET is_default=0');if($id){if(!DB::one('SELECT id FROM output_templates WHERE id=?',[$id]))json_response(['ok'=>false,'message'=>'فرم پیدا نشد.'],404);DB::exec('UPDATE output_templates SET name=?,paper_size=?,orientation=?,style=?,config_json=?,is_default=?,is_active=? WHERE id=?',[$name,$paper,$orientation,$style,$config,$default,$active,$id]);}else{DB::exec('INSERT INTO output_templates(name,paper_size,orientation,style,config_json,is_default,is_active,created_by)VALUES(?,?,?,?,?,?,?,?)',[$name,$paper,$orientation,$style,$config,$default,$active,$uid]);$id=(int)DB::pdo()->lastInsertId();}DB::pdo()->commit();audit($uid,null,'save','output_template',$id,null,['name'=>$name,'columns'=>$columns,'sections'=>$sections,'order'=>$order]);json_response(['ok'=>true,'message'=>'فرم خروجی ذخیره شد.','id'=>$id]);
 }
 if($action==='admin-output-template-delete'&&$method==='POST'){$id=(int)($in['id']??0);$row=DB::one('SELECT is_default FROM output_templates WHERE id=?',[$id]);if(!$row)json_response(['ok'=>false,'message'=>'فرم پیدا نشد.'],404);if((int)$row['is_default']===1)json_response(['ok'=>false,'message'=>'فرم پیش‌فرض قابل حذف نیست. ابتدا فرم دیگری را پیش‌فرض کنید.'],422);DB::exec('DELETE FROM output_templates WHERE id=?',[$id]);json_response(['ok'=>true,'message'=>'فرم خروجی حذف شد.']);}
 if($action==='bootstrap'){
  $companies=DB::all('SELECT * FROM companies WHERE user_id=? ORDER BY id DESC',[$uid]);
  $quotes=DB::all("SELECT q.id,q.quote_number,q.status,q.issue_date,q.total,COALESCE(cu.name,'') customer_name,c.name company_name FROM quotes q JOIN companies c ON c.id=q.company_id LEFT JOIN customers cu ON cu.id=q.customer_id AND cu.user_id=q.user_id WHERE q.user_id=? ORDER BY q.id DESC LIMIT 100",[$uid]);
  $templates=DB::all('SELECT id,name,paper_size,orientation,style,config_json,is_default FROM output_templates WHERE is_active=1 ORDER BY is_default DESC,id DESC');foreach($templates as &$template)$template['config']=json_decode((string)$template['config_json'],true)?:[];unset($template['config_json']);json_response(['ok'=>true,'data'=>['companies'=>$companies,'quotes'=>$quotes,'templates'=>$templates,'user'=>Auth::user()]]);
 }
 if($action==='company-save'&&$method==='POST'){
  $name=trim((string)($in['name']??''));if(mb_strlen($name)<2)json_response(['ok'=>false,'message'=>'نام شرکت الزامی است.'],422);
  $legalName=trim((string)($in['legal_name']??''));$nationalId=trim((string)($in['national_id']??''));$economicCode=trim((string)($in['economic_code']??''));$registrationNo=trim((string)($in['registration_no']??''));$phone=trim((string)($in['phone']??''));$mobile=trim((string)($in['mobile']??''));$email=trim((string)($in['email']??''));$website=trim((string)($in['website']??''));$address=trim((string)($in['address']??''));$postalCode=trim((string)($in['postal_code']??''));$brandColor=trim((string)($in['brand_color']??'#2563eb'));$bankInfo=trim((string)($in['bank_info']??''));$defaultTerms=trim((string)($in['default_terms']??''));
  if($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))json_response(['ok'=>false,'message'=>'ایمیل شرکت معتبر نیست.'],422);if(!preg_match('/^#[0-9a-fA-F]{6}$/',$brandColor))$brandColor='#2563eb';
  $tax=max(0,min(100,(float)($in['default_tax']??0)));$id=(int)($in['id']??0);
  DB::pdo()->beginTransaction();
  if($id){$own=DB::one('SELECT id FROM companies WHERE id=? AND user_id=?',[$id,$uid]);if(!$own)json_response(['ok'=>false,'message'=>'دسترسی غیرمجاز.'],403);
   DB::exec('UPDATE companies SET name=?,legal_name=?,national_id=?,economic_code=?,registration_no=?,phone=?,mobile=?,email=?,website=?,address=?,postal_code=?,brand_color=?,bank_info=?,default_terms=?,default_tax=? WHERE id=? AND user_id=?',[$name,$legalName?:null,$nationalId?:null,$economicCode?:null,$registrationNo?:null,$phone?:null,$mobile?:null,$email?:null,$website?:null,$address?:null,$postalCode?:null,$brandColor,$bankInfo?:null,$defaultTerms?:null,$tax,$id,$uid]);
  }else{DB::exec('INSERT INTO companies(user_id,name,legal_name,national_id,economic_code,registration_no,phone,mobile,email,website,address,postal_code,brand_color,bank_info,default_terms,default_tax)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$uid,$name,$legalName?:null,$nationalId?:null,$economicCode?:null,$registrationNo?:null,$phone?:null,$mobile?:null,$email?:null,$website?:null,$address?:null,$postalCode?:null,$brandColor,$bankInfo?:null,$defaultTerms?:null,$tax]);$id=(int)DB::pdo()->lastInsertId();}
  audit($uid,$id,'save','company',$id,null,['name'=>$name,'legal_name'=>$legalName,'national_id'=>$nationalId,'economic_code'=>$economicCode,'registration_no'=>$registrationNo]);DB::pdo()->commit();json_response(['ok'=>true,'message'=>'اطلاعات شرکت ذخیره شد.','id'=>$id]);
 }
 if($action==='quote-share'&&$method==='POST'){
  $quoteId=(int)($in['quote_id']??0);$quote=DB::one('SELECT q.*,c.name company_name FROM quotes q JOIN companies c ON c.id=q.company_id WHERE q.id=? AND q.user_id=?',[$quoteId,$uid]);if(!$quote)json_response(['ok'=>false,'message'=>'ابتدا پیش‌فاکتور را ذخیره کنید.'],404);
  $days=max(1,min(90,(int)($in['expires_days']??14)));$password=(string)random_int(100000,999999);$token=bin2hex(random_bytes(32));
  DB::exec('UPDATE quote_shares SET revoked_at=NOW() WHERE quote_id=? AND user_id=? AND revoked_at IS NULL',[$quoteId,$uid]);DB::exec('INSERT INTO quote_shares(quote_id,user_id,token_hash,password_hash,expires_at)VALUES(?,?,?,?,DATE_ADD(NOW(),INTERVAL ? DAY))',[$quoteId,$uid,hash('sha256',$token),password_hash($password,PASSWORD_DEFAULT),$days]);
  $link=url('q/'.$token);$sent=[];$errors=[];$email=trim((string)($in['email']??''));$mobile=Otp::normalize((string)($in['mobile']??''));
  if(!empty($in['send_email'])){if(!filter_var($email,FILTER_VALIDATE_EMAIL))$errors[]='ایمیل مشتری معتبر نیست.';else{$from=str_replace(["\r","\n"],'',(string)\App\Settings::get('mail.from_address','no-reply@'.($_SERVER['HTTP_HOST']??'localhost')));$subject='پیش‌فاکتور شماره '.$quote['quote_number'];$body="پیش‌فاکتور {$quote['quote_number']} از {$quote['company_name']}\n\nلینک مشاهده: {$link}\nرمز مشاهده: {$password}\nاعتبار لینک: {$days} روز";$headers="From: {$from}\r\nContent-Type: text/plain; charset=UTF-8";if(@mail($email,'=?UTF-8?B?'.base64_encode($subject).'?=',$body,$headers))$sent[]='email';else$errors[]='ارسال ایمیل توسط هاست ناموفق بود.';}}
  if(!empty($in['send_sms'])){if(!$mobile)$errors[]='شماره موبایل مشتری معتبر نیست.';else{[$ok,$msg]=Otp::sendPattern($mobile,(string)\App\Settings::get('sms.share_pattern_code',''),[(string)\App\Settings::get('sms.share_number_param','number')=>(string)$quote['quote_number'],(string)\App\Settings::get('sms.share_password_param','password')=>$password,(string)\App\Settings::get('sms.share_link_param','link')=>$link]);if($ok)$sent[]='sms';else$errors[]=$msg;}}
  audit($uid,(int)$quote['company_id'],'share','quote',$quoteId,null,['expires_days'=>$days,'channels'=>$sent]);json_response(['ok'=>true,'message'=>$errors?implode(' ',$errors):'لینک امن ساخته و ارسال شد.','data'=>['url'=>$link,'password'=>$password,'expires_days'=>$days,'sent'=>$sent,'errors'=>$errors]]);
 }
 if($action==='quote-share-revoke'&&$method==='POST'){$quoteId=(int)($in['quote_id']??0);DB::exec('UPDATE quote_shares SET revoked_at=NOW() WHERE quote_id=? AND user_id=? AND revoked_at IS NULL',[$quoteId,$uid]);json_response(['ok'=>true,'message'=>'لینک‌های فعال این پیش‌فاکتور لغو شدند.']);}
 if($action==='asset-upload'&&$method==='POST'){
  $companyId=(int)($_POST['company_id']??0);$kind=(string)($_POST['kind']??'');$map=['logo'=>'logo_path','stamp'=>'stamp_path','signature'=>'signature_path'];
  if(!isset($map[$kind])||!DB::one('SELECT id FROM companies WHERE id=? AND user_id=?',[$companyId,$uid])||!isset($_FILES['file']))json_response(['ok'=>false,'message'=>'درخواست نامعتبر است.'],422);
  $f=$_FILES['file'];if($f['error']!==UPLOAD_ERR_OK||$f['size']>2097152)json_response(['ok'=>false,'message'=>'فایل باید تصویر و حداکثر ۲ مگابایت باشد.'],422);
  $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);$ext=['image/png'=>'png','image/jpeg'=>'jpg','image/webp'=>'webp'][$mime]??null;if(!$ext)json_response(['ok'=>false,'message'=>'فرمت تصویر مجاز نیست.'],422);
  $dir=dirname(__DIR__).'/storage/uploads/companies/'.$companyId;if(!is_dir($dir))mkdir($dir,0750,true);$name=$kind.'-'.bin2hex(random_bytes(8)).'.'.$ext;$dest=$dir.'/'.$name;
  if(!move_uploaded_file($f['tmp_name'],$dest))json_response(['ok'=>false,'message'=>'ذخیره فایل ناموفق بود.'],500);$rel='storage/uploads/companies/'.$companyId.'/'.$name;
  DB::exec('UPDATE companies SET '.$map[$kind].'=? WHERE id=? AND user_id=?',[$rel,$companyId,$uid]);json_response(['ok'=>true,'path'=>$rel]);
 }
 if($action==='asset'&&$method==='GET'){
  $companyId=(int)($in['company_id']??0);$kind=(string)($in['kind']??'');$map=['logo'=>'logo_path','stamp'=>'stamp_path','signature'=>'signature_path'];$row=isset($map[$kind])?DB::one('SELECT '.$map[$kind].' path FROM companies WHERE id=? AND user_id=?',[$companyId,$uid]):null;
  if(!$row||!$row['path']){http_response_code(404);exit;}$file=dirname(__DIR__).'/'.$row['path'];if(!is_file($file)){http_response_code(404);exit;}header('Content-Type: '.(new finfo(FILEINFO_MIME_TYPE))->file($file));header('Cache-Control: private,max-age=3600');readfile($file);exit;
 }
 if($action==='customer-search'){
  $cid=ownCompany($uid,(int)($in['company_id']??0));$q='%'.trim((string)($in['q']??'')).'%';
  json_response(['ok'=>true,'data'=>DB::all('SELECT * FROM customers WHERE user_id=? AND company_id=? AND (name LIKE ? OR mobile LIKE ? OR national_id LIKE ?) ORDER BY updated_at DESC LIMIT 10',[$uid,$cid,$q,$q,$q])]);
 }
 if($action==='customer-save'&&$method==='POST'){
  $cid=ownCompany($uid,(int)($in['company_id']??0));$name=trim((string)($in['name']??''));if(mb_strlen($name)<2)json_response(['ok'=>false,'message'=>'نام مشتری الزامی است.'],422);
  $cols=['type','contact_name','mobile','phone','email','national_id','economic_code','registration_no','address','postal_code','notes'];$v=[];foreach($cols as $c)$v[]=trim((string)($in[$c]??($c==='type'?'business':'')));
  DB::exec('INSERT INTO customers(user_id,company_id,name,type,contact_name,mobile,phone,email,national_id,economic_code,registration_no,address,postal_code,notes)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$uid,$cid,$name,...$v]);json_response(['ok'=>true,'id'=>(int)DB::pdo()->lastInsertId()]);
 }
 if($action==='catalog-search'){
  $cid=ownCompany($uid,(int)($in['company_id']??0));$term=trim((string)($in['q']??''));
  $term=strtr($term,['ي'=>'ی','ى'=>'ی','ك'=>'ک','ۀ'=>'ه','ة'=>'ه']);$q='%'.$term.'%';
  $normalized="REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(name,'ي','ی'),'ى','ی'),'ك','ک'),'ۀ','ه'),'ة','ه')";
  json_response(['ok'=>true,'data'=>DB::all("SELECT * FROM catalog_items WHERE user_id=? AND company_id=? AND is_active=1 AND($normalized LIKE ? OR sku LIKE ?)ORDER BY last_used_at DESC,updated_at DESC LIMIT 20",[$uid,$cid,$q,$q])]);
 }
 if($action==='quote-get'){$id=(int)($in['id']??0);$q=DB::one('SELECT * FROM quotes WHERE id=? AND user_id=?',[$id,$uid]);if(!$q)json_response(['ok'=>false,'message'=>'سند پیدا نشد.'],404);$q['items']=DB::all('SELECT * FROM quote_items WHERE quote_id=? ORDER BY sort_order,id',[$id]);json_response(['ok'=>true,'data'=>$q]);}
 if($action==='quote-save'&&$method==='POST'){json_response(saveQuote($uid,$in));}
 if($action==='quote-finalize'&&$method==='POST'){
  $id=(int)($in['id']??0);$q=DB::one('SELECT * FROM quotes WHERE id=? AND user_id=?',[$id,$uid]);if(!$q)json_response(['ok'=>false,'message'=>'سند پیدا نشد.'],404);
  DB::pdo()->beginTransaction();DB::exec("UPDATE quotes SET status='issued',issued_at=NOW(),version=version+1 WHERE id=? AND user_id=? AND status='draft'",[$id,$uid]);
  $items=DB::all('SELECT catalog_item_id,unit_price FROM quote_items WHERE quote_id=? AND catalog_item_id IS NOT NULL',[$id]);foreach($items as $it){DB::exec('UPDATE catalog_items SET last_price=?,last_used_at=NOW()WHERE id=? AND user_id=?',[$it['unit_price'],$it['catalog_item_id'],$uid]);DB::exec('INSERT INTO price_history(catalog_item_id,company_id,price,source_quote_id)VALUES(?,?,?,?)',[$it['catalog_item_id'],$q['company_id'],$it['unit_price'],$id]);}DB::pdo()->commit();
  audit($uid,(int)$q['company_id'],'finalize','quote',$id,$q,null);json_response(['ok'=>true,'message'=>'پیش‌فاکتور صادر و قفل شد.']);
 }
 json_response(['ok'=>false,'message'=>'مسیر API پیدا نشد.'],404);
}catch(Throwable $e){try{if(DB::pdo()->inTransaction())DB::pdo()->rollBack();}catch(Throwable){}$requestId=bin2hex(random_bytes(6));error_log('[request:'.$requestId.'] '.$e->__toString());json_response(['ok'=>false,'message'=>env('APP_DEBUG')?$e->getMessage():'خطای داخلی رخ داد. کد پیگیری: '.$requestId],500);}

function ownCompany(int $uid,int $id):int{if(!$id||!DB::one('SELECT id FROM companies WHERE id=? AND user_id=?',[$id,$uid]))json_response(['ok'=>false,'message'=>'شرکت معتبر نیست.'],403);return$id;}
function audit(int $uid,?int $company,string $action,string $type,?int $id,mixed $before,mixed $after):void{$flags=JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_INVALID_UTF8_SUBSTITUTE;DB::exec('INSERT INTO audit_logs(user_id,company_id,action,entity_type,entity_id,before_data,after_data,ip,user_agent)VALUES(?,?,?,?,?,?,?,?,?)',[$uid,$company,$action,$type,$id,$before!==null?json_encode($before,$flags):null,$after!==null?json_encode($after,$flags):null,substr($_SERVER['REMOTE_ADDR']??'',0,45),substr($_SERVER['HTTP_USER_AGENT']??'',0,500)]);}
function saveQuote(int $uid,array $in):array{
 $cid=ownCompany($uid,(int)($in['company_id']??0));$company=DB::one('SELECT * FROM companies WHERE id=? AND user_id=?',[$cid,$uid]);$customerId=(int)($in['customer_id']??0);$customer=$customerId?DB::one('SELECT * FROM customers WHERE id=? AND company_id=? AND user_id=?',[$customerId,$cid,$uid]):null;
 $issueDate=(string)($in['issue_date']??'');$issueObject=DateTime::createFromFormat('!Y-m-d',$issueDate);if(!$issueObject||$issueObject->format('Y-m-d')!==$issueDate)json_response(['ok'=>false,'message'=>'تاریخ صدور جلالی را از تقویم انتخاب کنید.'],422);$validUntil=trim((string)($in['valid_until']??''));if($validUntil!==''){$validObject=DateTime::createFromFormat('!Y-m-d',$validUntil);if(!$validObject||$validObject->format('Y-m-d')!==$validUntil)json_response(['ok'=>false,'message'=>'تاریخ اعتبار را از تقویم انتخاب کنید.'],422);}
 if(!$customer){$cn=trim((string)($in['customer_name']??''));if(mb_strlen($cn)<2)json_response(['ok'=>false,'message'=>'مشتری را انتخاب یا ایجاد کنید.'],422);DB::exec('INSERT INTO customers(user_id,company_id,name,mobile,phone,national_id,economic_code,registration_no,address,postal_code)VALUES(?,?,?,?,?,?,?,?,?,?)',[$uid,$cid,$cn,(string)($in['customer_mobile']??''),(string)($in['customer_phone']??''),(string)($in['customer_national_id']??''),(string)($in['customer_economic_code']??''),(string)($in['customer_registration_no']??''),(string)($in['customer_address']??''),(string)($in['customer_postal_code']??'')]);$customerId=(int)DB::pdo()->lastInsertId();$customer=DB::one('SELECT * FROM customers WHERE id=?',[$customerId]);}
 $items=is_array($in['items']??null)?$in['items']:[];if(!$items)json_response(['ok'=>false,'message'=>'حداقل یک ردیف معتبر لازم است.'],422);$clean=[];$subtotal=0;$itemDiscount=0;$tax=0;
 foreach($items as $i=>$it){$name=trim((string)($it['name']??''));$qty=max(0,(float)($it['quantity']??0));$price=max(0,(float)($it['unit_price']??0));if(!$name||$qty<=0)continue;$dp=max(0,min(100,(float)($it['discount_percent']??0)));$tp=max(0,min(100,(float)($it['tax_percent']??0)));$base=round($qty*$price,2);$after=round($base*(1-$dp/100),2);$lineTax=round($after*$tp/100,2);$total=$after+$lineTax;$subtotal+=$base;$itemDiscount+=($base-$after);$tax+=$lineTax;$catalogId=(int)($it['catalog_item_id']??0);
  if(!$catalogId){DB::exec('INSERT INTO catalog_items(user_id,company_id,type,name,sku,description,unit,last_price,default_tax)VALUES(?,?,?,?,?,?,?,?,?)',[$uid,$cid,($it['type']??'product')==='service'?'service':'product',$name,(string)($it['sku']??''),(string)($it['description']??''),(string)($it['unit']??'عدد'),$price,$tp]);$catalogId=(int)DB::pdo()->lastInsertId();}
  $clean[]=['catalog_item_id'=>$catalogId,'type'=>($it['type']??'product')==='service'?'service':'product','name'=>$name,'description'=>(string)($it['description']??''),'sku'=>(string)($it['sku']??''),'unit'=>(string)($it['unit']??'عدد'),'quantity'=>$qty,'unit_price'=>$price,'discount_percent'=>$dp,'tax_percent'=>$tp,'line_subtotal'=>$base,'line_total'=>$total];
 }
 if(!$clean)json_response(['ok'=>false,'message'=>'حداقل یک ردیف معتبر لازم است.'],422);$discountType=($in['discount_type']??'amount')==='percent'?'percent':'amount';$dv=max(0,(float)($in['discount_value']??0));$discountBase=max(0,$subtotal-$itemDiscount);$da=$discountType==='percent'?round($discountBase*min($dv,100)/100,2):min($dv,$discountBase);$total=max(0,$subtotal-$itemDiscount-$da+$tax);$pre=max(0,min((float)($in['prepayment']??0),$total));$payable=$total-$pre;$id=(int)($in['id']??0);
 DB::pdo()->beginTransaction();
 if($id){$old=DB::one("SELECT * FROM quotes WHERE id=? AND user_id=? AND status='draft' FOR UPDATE",[$id,$uid]);if(!$old)json_response(['ok'=>false,'message'=>'فقط پیش‌نویس قابل ویرایش است.'],409);DB::exec('UPDATE quotes SET customer_id=?,issue_date=?,valid_until=?,customer_snapshot=?,subtotal=?,discount_type=?,discount_value=?,discount_amount=?,tax_amount=?,total=?,prepayment=?,payable=?,notes=?,terms=?,version=version+1 WHERE id=? AND user_id=?',[$customerId,$issueDate,$validUntil?:null,json_encode($customer,JSON_UNESCAPED_UNICODE),$subtotal,$discountType,$dv,$da,$tax,$total,$pre,$payable,(string)($in['notes']??''),(string)($in['terms']??''),$id,$uid]);DB::exec('DELETE FROM quote_items WHERE quote_id=?',[$id]);
 }else{$num=$company['quote_prefix'].'-'.str_pad((string)$company['next_quote_number'],5,'0',STR_PAD_LEFT);DB::exec('UPDATE companies SET next_quote_number=next_quote_number+1 WHERE id=? AND user_id=?',[$cid,$uid]);DB::exec('INSERT INTO quotes(user_id,company_id,customer_id,quote_number,issue_date,valid_until,company_snapshot,customer_snapshot,subtotal,discount_type,discount_value,discount_amount,tax_amount,total,prepayment,payable,notes,terms)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$uid,$cid,$customerId,$num,$issueDate,$validUntil?:null,json_encode($company,JSON_UNESCAPED_UNICODE),json_encode($customer,JSON_UNESCAPED_UNICODE),$subtotal,$discountType,$dv,$da,$tax,$total,$pre,$payable,(string)($in['notes']??''),(string)($in['terms']??'')]);$id=(int)DB::pdo()->lastInsertId();}
 foreach($clean as $n=>$it)DB::exec('INSERT INTO quote_items(quote_id,catalog_item_id,sort_order,type,name,description,sku,unit,quantity,unit_price,discount_percent,tax_percent,line_subtotal,line_total)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)',[$id,$it['catalog_item_id'],$n,...array_values(array_diff_key($it,['catalog_item_id'=>1]))]);
 DB::pdo()->commit();audit($uid,$cid,'save','quote',$id,null,['total'=>$total]);$saved=DB::one('SELECT quote_number FROM quotes WHERE id=? AND user_id=?',[$id,$uid]);return['ok'=>true,'message'=>'پیش‌نویس ذخیره شد.','id'=>$id,'quote_number'=>$saved['quote_number']??''];
}
